creation_rules:
  - unencrypted_regex: _(user|access_key)$
    age:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+Fa+dmnpPBYM0G7xPupl+GkVdF6YFmZ/NkpyqOzWoI  # lionel-panhaleux
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDlN9QsXPGklb1BhEyGYankvkqoKGFlls4O0UWKe/YKf  # deploy (GitHub Actions)
