name: CI Telemetry

on:
  workflow_run:
    workflows: [Test, Server Setup, Distribution Upgrade]
    types: [completed]

permissions:
  contents: read
  actions: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export traces to Grafana Cloud
        uses: corentinmusard/otel-cicd-action@f2d88ecf54d9dd3e01ea95e25f93603212ee93d3 # v4.0.1
        with:
          otlpEndpoint: ${{ secrets.GRAFANA_OTLP_ENDPOINT }}/v1/traces
          otlpHeaders: ${{ secrets.GRAFANA_OTLP_HEADERS }}
          otelServiceName: server-setup-ci
          runId: ${{ github.event.workflow_run.id }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
